export const CALENDAR_DATA = [
  {
    name: 'Adaira',
    color: 'rgb(220 130 18)',
    eventsByDay: [
      // Monday
      [
        {title: 'Class Meeting', start: '08:30'},
        {title: 'Art / PE / Music', start: '09:00'},
        {title: 'ELA Group 1', start: '09:30'},
        {title: 'ELA - Seesaw', start: '10:00'},
        {title: 'Break', start: '10:30'},
        {title: 'Math - Group 1', start: '11:00'},
        {title: 'Lunch', start: '11:30'},
        {title: 'Math - Seesaw', start: '12:15'},
        {title: 'Break', start: '12:45'},
        {title: 'Science / Social Studies', start: '13:00', end: '13:30'},
      ],
      // Tuesday
      [
        {title: 'Class Meeting', start: '08:30'},
        {title: 'Art / PE / Music', start: '09:00'},
        {title: 'ELA Group 1', start: '09:30'},
        {title: 'ELA - Seesaw', start: '10:00'},
        {title: 'Break', start: '10:30'},
        {title: 'Math - Group 1', start: '11:00'},
        {title: 'Lunch', start: '11:30'},
        {title: 'Math - Seesaw', start: '12:15'},
        {title: 'Break', start: '12:45'},
        {title: 'Science / Social Studies', start: '13:00', end: '13:30'},
      ],
      // Wednesday
      [
        {title: 'Class Meeting', start: '08:30'},
        {title: 'Art / PE / Music', start: '09:00'},
        {title: 'Reading - Live', start: '09:30'},
        {title: 'Break', start: '10:00'},
        {title: 'Math', start: '10:15'},
        {title: 'Break', start: '10:45'},
        {title: 'Science / Social Studies', start: '11:00'},
        {title: 'Lunch', start: '11:30', end: '12:15'},
      ],
      // Thursday
      [
        {title: 'Class Meeting', start: '08:30'},
        {title: 'Art / PE / Music', start: '09:00'},
        {title: 'ELA Group 1', start: '09:30'},
        {title: 'ELA - Seesaw', start: '10:00'},
        {title: 'Break', start: '10:30'},
        {title: 'Math - Group 1', start: '11:00'},
        {title: 'Lunch', start: '11:30'},
        {title: 'Math - Seesaw', start: '12:15'},
        {title: 'Break', start: '12:45'},
        {title: 'Science / Social Studies', start: '13:00', end: '13:30'},
      ],
      // Friday
      [
        {title: 'Class Meeting', start: '08:30'},
        {title: 'Art / PE / Music', start: '09:00'},
        {title: 'ELA Group 1', start: '09:30'},
        {title: 'ELA - Seesaw', start: '10:00'},
        {title: 'Break', start: '10:30'},
        {title: 'Math - Group 1', start: '11:00'},
        {title: 'Lunch', start: '11:30'},
        {title: 'Math - Seesaw', start: '12:15'},
        {title: 'Break', start: '12:45'},
        {title: 'Science / Social Studies', start: '13:00', end: '13:30'},
      ],
    ],
  },
  {
    name: 'Isla',
    color: 'rgb(181 63 172)',
    eventsByDay: [
      // Monday
      [
        {title: 'Welcome / SEL', start: '08:30'},
        {title: 'Writing', start: '09:00'},
        {title: 'Math', start: '09:45'},
        {title: 'Break', start: '10:30'},
        {title: 'PE - Live', start: '11:00'},
        {title: 'Reading', start: '11:30'},
        {title: 'Lunch', start: '12:00'},
        {title: 'Science / Social Studies', start: '12:45'},
        {title: 'Independent Work', start: '13:15', end: '14:30'},
      ],
      // Tuesday
      [
        {title: 'Welcome / SEL', start: '08:30'},
        {title: 'Writing', start: '09:00'},
        {title: 'Math', start: '09:45'},
        {title: 'Break', start: '10:30'},
        {title: 'PE - Seesaw', start: '11:00'},
        {title: 'Reading', start: '11:30'},
        {title: 'Lunch', start: '12:00'},
        {title: 'Science / Social Studies', start: '12:45', end: '13:15'},
        {title: 'Small Group - Sockeye', start: '13:20', end: '13:40'},
        {title: 'Independent Work', start: '13:40', end: '13:55'},
        {title: 'Music - Seesaw', start: '13:55', end: '14:25'},
      ],
      // Wednesday
      [
        {title: 'Welcome / SEL', start: '08:30'},
        {title: 'Writing', start: '09:00'},
        {title: 'Reading', start: '09:30'},
        {title: 'Independent Work / Small Groups', start: '10:00'},
        {title: 'Break', start: '10:30'},
        {title: 'PE - Seesaw', start: '11:00'},
        {title: 'Science / Social Studies', start: '11:30'},
        {title: 'Lunch', start: '12:00', end: '12:45'},
        {title: 'Class Connections / Community Meeting', start: '12:45'},
        {title: 'Independent Work', start: '13:15', end: '13:55'},
      ],
      // Thursday
      [
        {title: 'Welcome / SEL', start: '08:30'},
        {title: 'Writing', start: '09:00'},
        {title: 'Math', start: '09:45'},
        {title: 'Break', start: '10:30'},
        {title: 'PE - Seesaw', start: '11:00'},
        {title: 'Reading', start: '11:30'},
        {title: 'Lunch', start: '12:00'},
        {title: 'Science / Social Studies', start: '12:45'},
        {title: 'Independent Work', start: '13:15', end: '14:30'},
      ],
      // Friday
      [
        {title: 'Welcome / SEL', start: '08:30'},
        {title: 'Writing', start: '09:00'},
        {title: 'Math', start: '09:45'},
        {title: 'Break', start: '10:30'},
        {title: 'PE - Seesaw', start: '11:00'},
        {title: 'Reading', start: '11:30'},
        {title: 'Lunch', start: '12:00'},
        {title: 'Science / Social Studies', start: '12:45'},
        {title: 'Independent Work', start: '13:15', end: '13:55'},
        {title: 'Music - Seesaw', start: '13:55', end: '14:25'},
      ],
    ],
  },
  {
    name: 'Wellington',
    color: 'rgb(60 165 78)',
    eventsByDay: [
      // Monday
      [
        {title: 'Homeroom / Math / Science', start: '08:30'},
        {title: 'PE - Seesaw', start: '10:00'},
        {title: 'Break', start: '10:30'},
        {title: 'ELA', start: '11:00'},
        {title: 'Lunch', start: '12:00'},
        {title: 'Independent Work', start: '12:45'},
        {title: 'Art or Music', start: '13:20', end: '13:50'},
        {title: 'Science', start: '14:00', end: '14:30'},
      ],
      // Tuesday
      [
        {title: 'Homeroom / Math / Science', start: '08:30'},
        {title: 'PE - Live', start: '10:00'},
        {title: 'Break', start: '10:30'},
        {title: 'ELA', start: '11:00'},
        {title: 'Lunch', start: '12:00'},
        {title: 'Independent Work', start: '12:45'},
        {title: 'Small Groups', start: '13:10'},
        {title: 'Break', start: '13:30'},
        {title: 'Science', start: '14:00', end: '14:30'},
      ],
      // Wednesday
      [
        {title: 'Homeroom / Math / Science', start: '08:30'},
        {title: 'PE - Seesaw', start: '10:00'},
        {title: 'Break', start: '10:30'},
        {title: 'ELA', start: '11:00'},
        {title: 'Lunch', start: '12:00', end: '12:45'},
        {title: 'Office Hours', start: '12:45'},
        {title: 'Independent Work', start: '13:15', end: '13:45'},
      ],
      // Thursday
      [
        {title: 'Homeroom / Math / Science', start: '08:30'},
        {title: 'PE - Seesaw', start: '10:00'},
        {title: 'Break', start: '10:30'},
        {title: 'ELA', start: '11:00'},
        {title: 'Lunch', start: '12:00'},
        {title: 'Independent Work', start: '12:45'},
        {title: 'Art or Music', start: '13:20', end: '13:50'},
        {title: 'Social Studies', start: '14:00', end: '14:30'},
      ],
      // Friday
      [
        {title: 'Homeroom / Math / Science', start: '08:30'},
        {title: 'PE - Seesaw', start: '10:00'},
        {title: 'Break', start: '10:30'},
        {title: 'ELA', start: '11:00'},
        {title: 'Lunch', start: '12:00'},
        {title: 'Independent Work', start: '12:45'},
        {title: 'Social Studies', start: '13:10'},
        {title: 'Small Group 4', start: '13:10', end: '13:50'},
        {title: 'Social Studies', start: '14:00', end: '14:30'},
      ],
    ],
  },
];
